### ISSUE TITLE
fixed cloudflare url?

### ISSUE THREAD

**Issue by harrywang** [Bing-su/sd-webui-tunnels#10]
Thanks a lot for the great extension - I have been using this to expose webui for external use - but I get a different URL each time I restart the webui server - I don't know how tunneling works and wonder is it possible to have a fixed URL every time I start webui using --cloudflared? if yes, any pointers on how to do that?

Thanks!!!

PS. I googled and found a similar question at https://community.cloudflare.com/t/static-trycloudflare-com-url/328585

**Comment by Bing-su** [comment]
trycloudflare does not provide static URL feature.

Consider using [ngrok's static url feature](https://ngrok.com/blog-post/free-static-domains-ngrok-users) or [jprq](https://github.com/azimjohn/jprq).

**Comment by harrywang** [comment]
> trycloudflare does not provide static URL feature.
> 
> Consider using [ngrok's static url feature](https://ngrok.com/blog-post/free-static-domains-ngrok-users) or [jprq](https://github.com/azimjohn/jprq).

Thank you so much for your reply - is ngrok supported by this extension? I did not see the instructions in readme. Thanks!

**Comment by harrywang** [comment]
@Bing-su I found out ngrok was supported by a1111 out of the box but don't know how to use it - my knowledge is very limited for this:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/13909

I wonder whether you could help.

Thanks a lot!

**Comment by harrywang** [comment]
I got it:

```
--ngrok-options '{"domain":webui.mydomain.com}'
```
