### ISSUE TITLE
remote.moe running on http (colab)

### ISSUE THREAD

**Issue by bananasss00** [Bing-su/sd-webui-tunnels#2]
![изображение](https://user-images.githubusercontent.com/30229634/225400636-6c67ffe4-b7df-488f-bc5b-1e23aa0c5d43.png)

is it possible to force it to connect via https?

**Comment by Bing-su** [comment]
https://github.com/fasmide/remotemoe#https

## HTTPS
When typical HTTPS ports are forwarded (443, 3443, 4443, or 8443), just as HTTP, remotemoe picks an SSH tunnel to route traffic based on the Host-header.

HTTPS traffic, however, requires the forwarded service to talk TLS. It doesn't do any certificate validation as no-one will be able to provide a valid SSL certificate inside the SSH tunnel.

---

Remote.moe says that if you send the connection to a port like 443, you can get an https connection. but when I tried it locally, it didn't work. I think it's a certificate issue, but I don't have any ideas on how to fix it.
